Quasi/Quasi/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from base_app import views
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name="index"),
    url(r'^base_app/', include("base_app.urls")),
    url(r'^logout$', views.user_logout, name = "logout")
] +static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Quasi/base_app/urls.py
from django.conf.urls import url 
from . import views

app_name = "base_app"

urlpatterns = [
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', views.user_login, name="login"),
    url(r'^feedback/', views.feedback_form, name="feedback"),
    url(r'^wall/', views.wall, name="wall"),
    url(r'^trauma/', views.trauma, name="trauma"),
    url(r'^youto/', views.youto, name="youto")
]

Quasi/base_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileinfo(models.Model):
    user = models.OneToOneField(User)
    date_of_birth = models.DateField()
    profile_pic = models.ImageField(null = True, blank = True)

    def __str__(self):
        return self.user.username
class Feedback(models.Model):
    name = models.CharField(max_length=120)
    details = models.TextField()
    happy = models.BooleanField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name






# Create your models here.

Quasi/base_app/forms.py
from django import forms
from django.contrib.auth.models import User
from base_app.models import UserProfileinfo, Feedback

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError("the given email is already registered")
        return self.cleaned_data['email']
    class Meta():
       model = User
       fields = ('username', 'email', 'password')

class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileinfo
        fields = ('date_of_birth', 'profile_pic')

class FeedbackForm(forms.ModelForm):
    class Meta():
        model = Feedback
        exclude = []

Quasi/base_app/views.py
from django.shortcuts import render
from . import models, forms
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def index(request):
    return render(request, "base_app/index.html")

def register(request): 
    registered = False
    if request.method == "POST":  #CHECKING IF USER HAS SUBMITTED FORM
        user_form = forms.UserForm(request.POST) #ASSIGNING ANSWER TO VARIABLES
        profile_form = forms.UserInfoForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save() #CREATING USER

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = forms.UserForm() #IF USER HASN'T YET COMPLETED FORM, JUST SHOW THE HTML
        profile_form = forms.UserInfoForm()

    return render(request, "base_app/register.html", {"user_form" : user_form, "profile_form" : profile_form, "registered" : registered})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("AACOUNT NOT ACTIVE. PLEASE SIGN UP")
        else:
            print("Someone tried to log in and failed")
            print("Username: {} Password: {}".format(username, password))
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request, 'base_app/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required()
def wall(request):
    return render(request, 'base_app/wall.html')

@login_required
def trauma(request):
    if request.method == "POST":
        clave = request.POST.get("Clave")
        if clave.lower() == "marsexo":
            return render(request, 'base_app/buen_trauma.html', {})
        else:
            return render(request, 'base_app/mal_trauma.html', {})
    else:
        return render(request, 'base_app/pre_trauma.html', {})
@login_required
def youto(request):
    if request.method == "POST":
        clave = request.POST.get("Clave")
        if clave.lower() == "espaldicep":
            return render(request, 'base_app/buen_youto.html', {})
        else:
            return HttpResponse("Fallaste <b>guaton qlo</b>. Trata denuevo. Anda a la pagina anterior y ponte vivo")
    else:
        return render(request, 'base_app/pre_youto.html', {})
@login_required
def feedback_form(request):
    if request.method == "POST":
        form = forms.FeedbackForm(request.POST)

        if form.is_valid():
            form.save()
            return render(request, "base_app/thanks.html")
    else:
        form = forms.FeedbackForm()
        return render(request, "base_app/feedback.html", {"form" : form})




    

Quasi/templates/base_app/base.html
<!DOCTYPE html>
{% load staticfiles%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/png" href=" {% static 'images/faviconatzo.png'%}">
    <link rel="stylesheet" href="{% static 'mycss.css' %}">
    <title>Quasi homepage</title>
</head>
<body>
    <nav class="navbar  navbar-expand-lg navbar-light" style="background-color: rgb(255, 255, 255);">
      <div class="container">
        <a class="navbar-brand text-white" href="{% url 'index' %}"><img src="{% static "images/logatzo.svg" %}" alt="no foto" width="120" height="30"></a> <!-- quasi logo to home page-->
        <button class="navbar-toggler burger" name="button" > <!-- sandwich button when collapsed-->
          <span class="navbar-toggler-icon" data-toggle="collapse" data-target= "#navbarmenu"></span>
        </button>
        <div id="navbarmenu" class="collapse navbar-collapse"> 
          <ul class="navbar-nav mr-auto text-center"> <!-- user buttons left when isn't collapsed, center when is-->
           <!--  <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>-->
            <li class="nav-item">
              <a class="nav-link" href="{% url 'base_app:feedback' %}">Feedback</a>
            </li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'base_app:trauma' %}" >Seccion Traumajones</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'base_app:youto' %}" >Seccion Youto</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'base_app:wall' %}">Wall</a></li>
            {% endif %}
            <!-- user buttons when navbar is collapsed-->
            <div class="d-lg-none text-center" >
              {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
              {% else %}
                <li class="nav-item"><a class="nav-link"href="{% url 'base_app:login' %}">Login</a></li>
              {% endif %}
                <li class="nav-item"> <a class="nav-link" href="{% url 'base_app:register' %}" >Register</a></li>

            </div>

          </ul>

  
         <!-- user buttons when navbar isn't collapsed--> 
        </div>
        <div class="d-none d-lg-block">
          <ul class = "navbar-nav mr-5">
            <li class="nav-item right"  id= "register">
              <a class="nav-link right" href="{% url 'base_app:register' %}" id="register-text">Register</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item right"><a id= "userlog" class="nav-link" href="{% url 'logout' %}">Logout</a></li>
            {% else %}
              <li class="nav-item right"><a id="userlog" class="nav-link"href="{% url 'base_app:login' %}">Login</a></li>
            {% endif %}
        </ul>
        </div>

      </div>
        
  
      </nav>

    
    {% block body_block%}
    {% endblock%}

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

Quasi/templates/base_app/buen_trauma.html
{% extends 'base_app/base.html' %}
{%load staticfiles %}
{% block body_block %}
<div class="jumbotron jumbotron-fluid text-center">
    <p>HAS TRAUMADO! WELCOME TO THE SEXOOOOOOO</p>
    <img src="{%static 'images/fatty.png'%}" alt="Where is the trauma" width="464" height="617.6" class="rounded mx-auto d-block" >>
</div>

{% endblock %}

Quasi/templates/base_app/buen_youto.html
{% extends 'base_app/base.html' %}
{%load staticfiles %}
{% block body_block %}
<div class="jumbotron jumbotron-fluid text-center">
    <div class="container">

        <p>HAS TRAUMADO! Anda a presbanquiar</p>
        <img src="{%static 'images/youto3.jpg'%}" alt="Where is the trauma" width="464" height="617.6" class="rounded mx-auto d-block" >>
        <p>Un recuerdo de cuando nos acompañó Jimmy (Damelo siempre). El segundo muerto del sportlife y gran amante del plan #BetelEsYoutopia</p>
        <img src="{% static 'images/conjames.jpg' %}" alt="no sauna" width="464" height="617.6" class="rounded mx-auto d-block" >

    </div>
    
    
</div>

{% endblock %}

Quasi/templates/base_app/feedback.html
{% extends 'base_app/base.html' %}


{% block body_block%}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1>Porfa dame tu feedback</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p}}
            <p>Checkea happy si estás feliz con quasi's webpage</p>
            <button type="submit" class="btn btn-primary text-center">Enviar</button>
        </form>
    </div>

</div>



{% endblock %}

Quasi/templates/base_app/index.html
{% extends 'base_app/base.html' %}
{% load staticfiles %}
{% block body_block%}
<div class="jumbotron jumbotron-fluid text-center">
    <h1><strong> MI PAGINA WEB</strong></h1>
    <p>Bienvenutti a la página del father, the one and only, Quasi v2.0. He webeado caleta pa hacer esta cagada de sitio  (el primero wooohooo)</p>
    <p>Asique aprovechen la wea y sino me chupan un huevo</p>
    <p>Les dejo un quasi todo mino pa su deleite</p>
    <img src="{% static 'images/landingquasi.JPG' %}" alt="NoQuasi" height="416" width="216">
</div>

{% endblock %}

Quasi/templates/base_app/login.html
{% extends 'base_app/base.html' %}
{% block body_block%}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1>LOGEATE PA DENTRO</h1>

        <form action="{% url 'base_app:login' %}" method="POST">
            {% csrf_token%}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder=" username">

            <label for="password">Password:</label>
            <input type="password" name="password" placeholder="password">
            <input type="submit" value="login">
        </form>
        <br>
        <p>SI NO TENI CUENTA (PERKIN) <a href="{% url 'base_app:register'%}">REGISTRATE ACÁ</a></p>

    </div>
    
</div>
{% endblock %}

Quasi/templates/base_app/mal_trauma.html
{% extends 'base_app/base.html' %}
{% block body_block %}
<div class="jumbotron jumbotron-fluid text-center">
    <p>PONTE VIO ESA NO ES LA CLAVE. APRETA SECCION TRAUMAJONES DENUEVO (Hint:mar....)</p>
</div>

{% endblock %}

Quasi/templates/base_app/pre_trauma.html
{% extends 'base_app/base.html' %}
{% block body_block %}
<div class="jumbotron jumbotron-fluid text-center">
    <p>Para acceder a la sección traumajones, ingresa la clave ultraquasisecreta (Hint: globos)</p>
    <form action="{% url 'base_app:trauma' %}" method="POST">
        {% csrf_token %}
        <label for="Clave"></label>
        <input type="text" name="Clave" placeholder="Acá va la clave traumador">


    </form>
    
</div>

{% endblock %}

Quasi/templates/base_app/pre_youto.html
{% extends 'base_app/base.html' %}
{% block body_block %}
<div class="jumbotron jumbotron-fluid text-center">
    <p>Para acceder a la sección YOUTO, ingresa la clave ultraquasisecreta (Hint: dia favorito del reb)</p>
    <form action="{% url 'base_app:youto' %}" method="POST">
        {% csrf_token %}
        <label for="Clave"></label>
        <input type="text" name="Clave" placeholder="Acá va la clave traumador">


    </form>
    
</div>

{% endblock %}

Quasi/templates/base_app/register.html
{% extends 'base_app/base.html' %}


{% block body_block%}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        {% if registered %}
        <h1>Thank you for registering</h1>
        {% else %}
        <h1>Register here</h1>
        <h3>Fill out the form</h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p}}
            {{ profile_form.as_p}}
            <button type="submit" class="btn btn-primary text-center">SIGN-UP!</button>
        {% endif %}
        </form>

        <p>Date format: mm/dd/yyyy</p>
    </div>

</div>



{% endblock %}

Quasi/templates/base_app/thanks.html
{% extends 'base_app/base.html' %}


{% block body_block%}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1>GRACIAS UWU</h1>
    </div>

</div>



{% endblock %}

Quasi/templates/base_app/wall.html
{% extends 'base_app/base.html' %}
{%load staticfiles %}

{% block body_block%}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1>Si ves esto es porque estas logged in. No tiene ningun uso por ahora y pronto será el quasi blog. Sigue sapeando</h1>
        <p>OH AH OH QUISHITO</p>
    </div>
</div>


{% endblock %}